/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 riggedhand.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/riggedhand.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.219, -1.611, -0.127]}>
        <primitive object={nodes.Bone} />
        <primitive object={nodes.Bone017} />
        <mesh geometry={nodes.hand.geometry} material={nodes.hand.material} position={[0.071, 1.611, -0.63]} rotation={[0, -1.571, 0]} scale={-1} />
      </group>
    </group>
  )
}

useGLTF.preload('/riggedhand.gltf')
